blank_issues_enabled: false
contact_links:
    - name: ðŸ“ƒ Documentation Issue
      url: https://github.com/community-scripts/ProxmoxVE/issues/new/choose
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: ðŸ¤” Questions and Help
      url: https://github.com/community-scripts/ProxmoxVE/discussions
      about: This issue tracker is not for support questions. Please refer to the community's help.
    - name: ðŸ’» Discord
      url: https://discord.gg/UHrpNWGwkH
      about: Feel free to join our Discord for Talking, Homelab and so on.